// src/components/app/channels/text/Embed.svelte
<script lang="ts">
    const { embed } = $props<{ embed: any }>();

    function getEmbedStyle(embed: any) {
        const maxDim = 1200;
        const w = embed?.width;
        const h = embed?.height;
        if (w) {
            const useW = Math.min(w, maxDim);
            return `width:${useW}px; height:auto; max-width:100%; max-height:60vh;`;
        }
        if (h) {
            const useH = Math.min(h, maxDim);
            return `height:${useH}px; width:auto; max-width:100%; max-height:60vh;`;
        }
        return `max-width:100%; max-height:60vh; height:auto;`;
    }

    function isGIFEmbed(embed: any) {
        if (!embed) return false;
        if (embed.type === "Image")
            return !!embed.url?.startsWith("https://static.klipy.com");
        if (embed.type === "Website") {
            const orig = embed.originalUrl ?? "";
            return (
                embed.specialContent?.type === "GIF" ||
                orig.startsWith("https://tenor.com") ||
                orig.startsWith("https://klipy.com") ||
                orig.startsWith("https://static.klipy.com")
            );
        }
        return false;
    }

    let src: string | null = $state(null);

    $effect(() => {
        src =
            embed?.url ??
            embed?.proxiedURL ??
            embed?.originalUrl ??
            embed?.previewUrl ??
            embed?.image?.url ??
            embed?.image?.proxiedURL ??
            embed?.image?.originalUrl ??
            embed?.video?.url ??
            embed?.video?.proxiedURL ??
            embed?.video?.originalUrl ??
            null;

        if (embed && !src) {
            console.warn("Embed missing src fields", embed);
        }
    });
</script>

{#if embed.type === "Image"}
    <img
        loading="lazy"
        {src}
        alt={embed.title ?? "embed-image"}
        class="object-contain block"
        width={embed.width}
        height={embed.height}
        style={getEmbedStyle(embed)}
    />
{:else if embed.type === "Video"}
    <video
        aria-hidden="true"
        controls
        preload="metadata"
        {src}
        class="w-full h-auto"
    ></video>
{:else if embed.type === "Website"}
    {@const gif = isGIFEmbed(embed)}
    {@const image = embed.image}
    {@const video = embed.video}
    {#if image}
        <img
            loading="lazy"
            {src}
            alt={embed.title ?? "embed-image"}
            class="object-contain block"
            width={image.width}
            height={image.height}
            style={getEmbedStyle(image)}
        />
    {:else if video}
        <video
            loop={gif}
            muted={gif}
            autoplay={gif}
            controls={!gif}
            preload="metadata"
            {src}
            class="w-full h-auto"
        ></video>
    {/if}
{/if}

// components/ui/components/features/messaging/elements/Embed.tsx
import { Match, Switch } from "solid-js";

import {
  ImageEmbed,
  MessageEmbed,
  TextEmbed as TextEmbedClass,
  VideoEmbed,
  WebsiteEmbed,
} from "stoat.js";
import { css } from "styled-system/css";

import { useModals } from "@revolt/modal";
import { SizedContent } from "@revolt/ui/components/utils";

import { TextEmbed } from "./TextEmbed";

/**
 * Render a given embed
 */
export function Embed(props: { embed: MessageEmbed }) {
  const { openModal } = useModals();

  /**
   * Whether the embed is a GIF
   */
  const isGIF = () =>
    props.embed.type === "Website" &&
    ((props.embed as WebsiteEmbed).specialContent?.type === "GIF" ||
      (props.embed as WebsiteEmbed).originalUrl?.startsWith(
        "https://tenor.com",
      ) || (props.embed as WebsiteEmbed).originalUrl?.startsWith(
        "https://klipy.com"
      ) || (props.embed as WebsiteEmbed).originalUrl?.startsWith(
        "https://static.klipy.com"
      ));

  /**
   * Whether there is a video
   */
  const video = () =>
    (props.embed.type === "Video"
      ? (props.embed as VideoEmbed)
      : isGIF() && (props.embed as WebsiteEmbed).video) || undefined;

  /**
   * Whether there is a image
   */
  const image = () =>
    (props.embed.type === "Image"
      ? (props.embed as ImageEmbed)
      : isGIF() && (props.embed as WebsiteEmbed).image) || undefined;

  return (
    <Switch fallback={`Could not render ${props.embed.type}!`}>
      <Match when={image()}>
        <SizedContent width={image()!.width} height={image()!.height}>
          <img
            // bypass proxy for known GIF providers
            src={isGIF() ? image()!.url : image()!.proxiedURL}
            loading="lazy"
            class={css({ cursor: "pointer" })}
            onClick={() =>
              openModal({
                type: "image_viewer",
                embed: image(),
              })
            }
          />
        </SizedContent>
      </Match>
      <Match when={video()}>
        <SizedContent width={video()!.width} height={video()!.height}>
          <video
            loop={isGIF()}
            muted={isGIF()}
            autoplay={isGIF()}
            controls={!isGIF()}
            preload="metadata"
            // bypass proxy for known GIF providers
            src={isGIF() ? video()!.url : video()!.proxiedURL}
            class={css({ cursor: isGIF() ? "pointer" : "unset" })}
            onClick={() =>
              isGIF() &&
              openModal({
                type: "image_viewer",
                gif: video(),
              })
            }
          />
        </SizedContent>
      </Match>
      <Match
        when={props.embed.type === "Website" || props.embed.type === "Text"}
      >
        <TextEmbed embed={props.embed as WebsiteEmbed | TextEmbedClass} />
      </Match>
      <Match when={props.embed.type === "None"}> </Match>
    </Switch>
  );
}
